# exec = export SLURP_ARGS='-d -c DDE1FFBB -b 3E456544 -s 00000000'

general {
    col.active_border = rgb(091c34)
    col.inactive_border = rgb(091c34)
}

misc {
    background_color = rgb(000000)
}

# plugin {
#     hyprbars {
#         # Honestly idk if it works like css, but well, why not
#         bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
#         bar_height = 30
#         bar_padding = 10
#         bar_button_padding = 5
#         bar_precedence_over_border = true
#         bar_part_of_window = true

#         bar_color = rgba(0F141CFF)
#         col.text = rgba(DEE2EFFF)


#         # example buttons (R -> L)
#         # hyprbars-button = color, size, on-click
#         hyprbars-button = rgb(DEE2EF), 13, 󰖭, hyprctl dispatch killactive
#         hyprbars-button = rgb(DEE2EF), 13, 󰖯, hyprctl dispatch fullscreen 1
#         hyprbars-button = rgb(DEE2EF), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
#     }
# }

windowrule = border_color rgba(A7C8FFAA) rgba(A7C8FF77), match:pin true
# windowrule = border_color rgba(FFB2BCAA) rgba(FFB2BC77), match:pin true