# ----------------------------------------------------- 
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "Dynamic"
# credit https://github.com/mylinuxforwork/dotfiles
# ----------------------------------------------------- 

animations {
    enabled = true
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    
    
    animation = windows, 1, 20, wind, slide
    animation = windowsIn, 1, 20, winIn, slide
    animation = windowsOut, 1, 20, winOut, slide
    animation = fade, 1, 20, default
    animation = workspaces, 1, 20, wind
    animation = fadeLayersIn, 1, 20, overshot
    animation = windowsIn, 1, 20, md3_decel, popin 60%


}
