wallpaper {
    monitor = eDP-2
    path = /home/talal/Pictures/Wallpapers/back.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/talal/Pictures/Wallpapers/back.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/talal/Pictures/Wallpapers/back.jpg 
    fit_mode = cover
}

splash = false
