$scrPath = $HOME/.local/share/bin # set scripts path


# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor = ,preferred,auto,auto


# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/
exec-once = hyprpaper
exec-once = $scrPath/resetxdgportal.sh
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = waybar
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = PATH,$PATH:$scrPath
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = DESKTOP_SESSION,hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = MOZ_ENABLE_WAYLAND,1
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24


# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# See https://wiki.hyprland.org/Configuring/Variables/


input {
    kb_layout = us,ara
    follow_mouse = 1
    numlock_by_default = true
    # repeat_delay = 500
    # repeat_rate = 35
    
    # Global pointer fallback (can leave it as adaptive or flat)
    accel_profile = adaptive
    sensitivity = 0.35 

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        scroll_factor = 0.45  # Increased slightly to make low polling rate scrolling feel smoother
        drag_lock = false 
    }
}

device {
    name = attack-shark-x3 
    accel_profile = flat
    sensitivity = 0
    natural_scroll = no
}

device {
    name =  synps/2-synaptics-touchpad
    sensitivity = 0.2       
    accel_profile = adaptive  
    }

# See https://wiki.hyprland.org/Configuring/Variables/

gestures {
	gesture = 3, horizontal, workspace
}


# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/

dwindle {
    pseudotile = yes
    preserve_split = yes
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/

master {
    new_status = master
}


# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

# See https://wiki.hyprland.org/Configuring/Variables/

misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
    force_zero_scaling = true
}

#debug {
#    overlay = true
#}

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = $HOME/.config/hypr/themes/colors.conf # wallbash color override
source = $HOME/.config/hypr/animations.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windowrules.conf
source = $HOME/.config/hypr/themes/common.conf # shared theme settings
source = $HOME/.config/hypr/themes/theme.conf # theme specific settings

source = $HOME/.config/hypr/monitors.conf # initially empty, to be configured by user and remains static
